export function renderWindowsPrintScript(): string {
  return [
    "param([string]$pickCode, [string]$buyerName, [string]$orderId, [string]$price)",
    "Add-Type -AssemblyName System.Drawing;",
    "$doc = New-Object System.Drawing.Printing.PrintDocument;",
    "$doc.DocumentName = 'Live Order Label';",
    "$doc.DefaultPageSettings.PaperSize = New-Object System.Drawing.Printing.PaperSize('1.5x1', 100, 150);",
    "$doc.DefaultPageSettings.Landscape = $true;",
    "$doc.DefaultPageSettings.Margins = New-Object System.Drawing.Printing.Margins(0, 0, 0, 0);",
    "$doc.add_PrintPage({",
    "param($sender, $event);",
    "$graphics = $event.Graphics;",
    "$graphics.PageUnit = [System.Drawing.GraphicsUnit]::Display;",
    "$graphics.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::HighQuality;",
    "$graphics.TextRenderingHint = [System.Drawing.Text.TextRenderingHint]::ClearTypeGridFit;",
    "$black = [System.Drawing.Brushes]::Black;",
    "$metaFont = New-Object System.Drawing.Font('Arial', 5.5, [System.Drawing.FontStyle]::Bold);",
    "$buyerFont = New-Object System.Drawing.Font('Arial', 13, [System.Drawing.FontStyle]::Bold);",
    "$pickFont = New-Object System.Drawing.Font('Arial', 19, [System.Drawing.FontStyle]::Bold);",
    "$noteFont = New-Object System.Drawing.Font('Arial', 5.5, [System.Drawing.FontStyle]::Bold);",
    "$left = New-Object System.Drawing.StringFormat;",
    "$left.Trimming = [System.Drawing.StringTrimming]::EllipsisCharacter;",
    "$left.FormatFlags = [System.Drawing.StringFormatFlags]::NoWrap;",
    "$right = New-Object System.Drawing.StringFormat;",
    "$right.Alignment = [System.Drawing.StringAlignment]::Far;",
    "$right.FormatFlags = [System.Drawing.StringFormatFlags]::NoWrap;",
    "$graphics.DrawString(('ORDER ' + $orderId), $metaFont, $black, (New-Object System.Drawing.RectangleF(14, 5, 76, 12)), $left);",
    "if ($price) { $graphics.DrawString($price, $metaFont, $black, (New-Object System.Drawing.RectangleF(92, 5, 40, 12)), $right); }",
    "$graphics.DrawLine([System.Drawing.Pens]::Black, 14, 18, 132, 18);",
    "$graphics.DrawString($buyerName, $buyerFont, $black, (New-Object System.Drawing.RectangleF(14, 22, 118, 19)), $left);",
    "$graphics.DrawString($pickCode, $pickFont, $black, (New-Object System.Drawing.RectangleF(14, 43, 118, 31)), $left);",
    "$graphics.DrawString('*This label peels off easily.', $noteFont, $black, (New-Object System.Drawing.RectangleF(14, 82, 118, 11)), $left);",
    "$event.HasMorePages = $false;",
    "});",
    "$doc.Print();"
  ].join("\n");
}
